#############################################################################
# Makefile for building: mythmpd
# Generated by qmake (1.07a) (Qt 3.3.7) on: Fri Sep 12 13:49:22 2008
# Project:  mythmpd.pro
# Template: subdirs
# Command: $(QMAKE) -o Makefile mythmpd.pro
#############################################################################

MAKEFILE =	Makefile
QMAKE    =	qmake
DEL_FILE =    rm -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p
INSTALL_FILE= 
INSTALL_DIR = 
SUBTARGETS =	 \
		sub-mythmpd

first: all

all: Makefile $(SUBTARGETS)

mythmpd/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "mythmpd" || $(MKDIR) "mythmpd"
	cd mythmpd && $(QMAKE) mythmpd.pro -o $(MAKEFILE)
sub-mythmpd: mythmpd/$(MAKEFILE) FORCE
	cd mythmpd && $(MAKE) -f $(MAKEFILE)

Makefile: mythmpd.pro  /usr/share/qt3/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile mythmpd.pro
qmake: qmake_all
	@$(QMAKE) -o Makefile mythmpd.pro

all: $(SUBTARGETS)
qmake_all: mythmpd/$(MAKEFILE)
	 ( [ -d mythmpd ] && cd mythmpd ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
clean uicables mocables uiclean mocclean lexclean yaccclean : qmake_all FORCE
	 ( [ -d mythmpd ] && cd mythmpd ; $(MAKE) -f $(MAKEFILE) $@; ) || true
uninstall_subdirs: qmake_all FORCE
	 ( [ -d mythmpd ] && cd mythmpd ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
install_subdirs: qmake_all FORCE
	 ( [ -d mythmpd ] && cd mythmpd ; $(MAKE) -f $(MAKEFILE) install; ) || true
distclean: qmake_all FORCE
	 ( [ -d mythmpd ] && cd mythmpd ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true

install:  install_subdirs

uninstall:  uninstall_subdirs

FORCE:

