#############################################################################
# Makefile for building: mythmpd
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Apr 21 15:53:49 2013
# Project:  mythmpd.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile mythmpd.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-mythmpd

mythmpd//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) mythmpd/ || $(MKDIR) mythmpd/ 
	cd mythmpd/ && $(QMAKE) /mnt/Data/Home/cjd/tmp/mythmpd/mythmpd/mythmpd.pro -o $(MAKEFILE)
sub-mythmpd-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) mythmpd/ || $(MKDIR) mythmpd/ 
	cd mythmpd/ && $(QMAKE) /mnt/Data/Home/cjd/tmp/mythmpd/mythmpd/mythmpd.pro -o $(MAKEFILE)
sub-mythmpd: mythmpd//$(MAKEFILE) FORCE
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE)
sub-mythmpd-make_default: mythmpd//$(MAKEFILE) FORCE
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE) 
sub-mythmpd-make_first: mythmpd//$(MAKEFILE) FORCE
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE) first
sub-mythmpd-all: mythmpd//$(MAKEFILE) FORCE
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE) all
sub-mythmpd-clean: mythmpd//$(MAKEFILE) FORCE
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE) clean
sub-mythmpd-distclean: mythmpd//$(MAKEFILE) FORCE
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE) distclean
sub-mythmpd-install_subtargets: mythmpd//$(MAKEFILE) FORCE
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE) install
sub-mythmpd-uninstall_subtargets: mythmpd//$(MAKEFILE) FORCE
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: mythmpd.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile mythmpd.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile mythmpd.pro

qmake_all: sub-mythmpd-qmake_all FORCE

make_default: sub-mythmpd-make_default FORCE
make_first: sub-mythmpd-make_first FORCE
all: sub-mythmpd-all FORCE
clean: sub-mythmpd-clean FORCE
distclean: sub-mythmpd-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-mythmpd-install_subtargets FORCE
uninstall_subtargets: sub-mythmpd-uninstall_subtargets FORCE

sub-mythmpd-check: mythmpd/$(MAKEFILE)
	cd mythmpd/ && $(MAKE) -f $(MAKEFILE) check
check: sub-mythmpd-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

